# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import magna_pb2 as magna__pb2


class InferenceServiceStub(object):
    """=============================================================================
    Magna Middleware — gRPC Inference Service
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/magna.InferenceService/Infer',
                request_serializer=magna__pb2.InferenceRequest.SerializeToString,
                response_deserializer=magna__pb2.InferenceResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/magna.InferenceService/HealthCheck',
                request_serializer=magna__pb2.HealthRequest.SerializeToString,
                response_deserializer=magna__pb2.HealthResponse.FromString,
                )
        self.UploadModel = channel.stream_unary(
                '/magna.InferenceService/UploadModel',
                request_serializer=magna__pb2.ModelChunk.SerializeToString,
                response_deserializer=magna__pb2.UploadModelResponse.FromString,
                )
        self.PrepareContext = channel.unary_unary(
                '/magna.InferenceService/PrepareContext',
                request_serializer=magna__pb2.PrepareContextRequest.SerializeToString,
                response_deserializer=magna__pb2.PrepareContextResponse.FromString,
                )
        self.ListModels = channel.unary_unary(
                '/magna.InferenceService/ListModels',
                request_serializer=magna__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=magna__pb2.ListModelsResponse.FromString,
                )


class InferenceServiceServicer(object):
    """=============================================================================
    Magna Middleware — gRPC Inference Service
    =============================================================================

    """

    def Infer(self, request, context):
        """Run inference on an image and return raw output tensor + optional labels.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check / readiness probe.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadModel(self, request_iterator, context):
        """Upload a model artifact (DLC, context binary, etc.) to the server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareContext(self, request, context):
        """Generate a QNN context binary from a deployed DLC on the device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """List available models on the device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=magna__pb2.InferenceRequest.FromString,
                    response_serializer=magna__pb2.InferenceResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=magna__pb2.HealthRequest.FromString,
                    response_serializer=magna__pb2.HealthResponse.SerializeToString,
            ),
            'UploadModel': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadModel,
                    request_deserializer=magna__pb2.ModelChunk.FromString,
                    response_serializer=magna__pb2.UploadModelResponse.SerializeToString,
            ),
            'PrepareContext': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareContext,
                    request_deserializer=magna__pb2.PrepareContextRequest.FromString,
                    response_serializer=magna__pb2.PrepareContextResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=magna__pb2.ListModelsRequest.FromString,
                    response_serializer=magna__pb2.ListModelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'magna.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """=============================================================================
    Magna Middleware — gRPC Inference Service
    =============================================================================

    """

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/magna.InferenceService/Infer',
            magna__pb2.InferenceRequest.SerializeToString,
            magna__pb2.InferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/magna.InferenceService/HealthCheck',
            magna__pb2.HealthRequest.SerializeToString,
            magna__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadModel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/magna.InferenceService/UploadModel',
            magna__pb2.ModelChunk.SerializeToString,
            magna__pb2.UploadModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PrepareContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/magna.InferenceService/PrepareContext',
            magna__pb2.PrepareContextRequest.SerializeToString,
            magna__pb2.PrepareContextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/magna.InferenceService/ListModels',
            magna__pb2.ListModelsRequest.SerializeToString,
            magna__pb2.ListModelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
